package:
  name: kernax
  version: 0.0.1

source:
  git_url: # https://gitlab.com/drti/kernax.git

build:
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - setuptools

  run:
    - python>=3.9
    - jax
    - blackjax==0.9.6
    - numpy
    - scipy
    - tqdm
    - pandas
    - matplotlib
    - scikit-learn
    - typing_extensions

test:
  imports:
    - kernax

about:
  home: https://gitlab.com/drti/kernax
